### ISSUE TITLE
What happens when a release step fails?

### ISSUE THREAD

**Issue by airtonix** [bumped/bumped#66]

**Comment by Kikobeats** [comment]
good question,

sometimes one task could be fail, but the idea is propose a scenario when all tasks doesn't fail.

why?
- That's the thing that happens major part of time.
- Handle errors per each task make the workflow too complicate.

Normally, when bumped fails is because test are broken, not internet connection or something similar.

In this case, just add a first task step to do all the necessary checks and exit with an error if something is not ready.

I close that but feel free to reply 😄
