### ISSUE TITLE
Feature Request: version convention

### ISSUE THREAD

**Issue by malachib** [bumped/bumped#72]
I just discovered your software and really like it; one thing though: I am in the .NET Core world, and we're fond of versioning things like this:

1.0.1-alpha001 -> 1.0.1-alpha002

I know that's considerably more complex than X.Y.Z, but it's a feature I'd love to have

**Comment by Kikobeats** [comment]
Hey,


This request is difficult to handle it, mainly because bumped is based in the [semver](https://www.npmjs.com/package/semver) api.

The equivalente way in semver could be:

```
$ semver 1.2.4-beta.0 -i prerelease
1.2.4-beta.1
```

This means that if your current version is `1.2.4-beta.0` you can do `bumped release prerelease`

On the other hand, always you can setup the nex version manually. Try this:

```
$ bumped release 1.0.1-alpha001
```

**Comment by malachib** [comment]
The manual version is encouraging.  I'll roll with that for now!  

Perhaps there could be an optional versioning template:

Something like - "{X}.{Y}.{branch}-{%05:Z}".  I am slightly hesitant to suggest it, because I like what semver is going for - and it isn't that!  But a lot of us can't conform exactly to their ideal.

**Comment by Kikobeats** [comment]
Thanks for the suggestions but currently I prefer keep versioning simple. I close that! Feel free to extend docs or open new issues
